### ISSUE TITLE
Impossible to light up all leds

### ISSUE THREAD

**Issue by sokol07** [OpenScanEu/OpenScan2#16]
Hi,
In the newest software version of OpenScan (beta for classic with arducam) it is impossible to turn on both LEDs at the same time.
Is it a matter of heat dissipation or power consumption?
If not, it can be easily solved in nodered by modifying the ringlight slider:
![image](https://user-images.githubusercontent.com/39523480/157232198-6b11edd3-fb9b-4e40-a0c8-39a63bee904c.png)
and consecutive code piece:
![image](https://user-images.githubusercontent.com/39523480/157232315-505e29e6-54d0-4f40-817c-82f65084527f.png)

**Comment by OpenScanFan** [comment]
or you could just change in line 12 to  "ringlight(2,True)" and not have to enter lines 13,14 and 15 like you have

**Comment by sokol07** [comment]
In this case you would only have horizontal+vertical LEDs or all turned on, without option to have only diagonal ones. Adding the fourth case let's you have all possible combinations.

**Comment by OpenScanFan** [comment]
yeah, I know, but why would you want horizontal or vertical anyway? what difference would it make?

**Comment by sokol07** [comment]
I guess that may be useful - due to the object shape, maybe some polarizing benefits or something like that. I believe this may be useful at some point, maybe in future revisions different types of LEDs could be used, for example with different light color. That's how it's done in industrial vision systems, there are multiple diodes, for example red, blue, green and IR. I think this feature should be left as this could be useful at some point. For now: I think it may happen that choosing one set over another can give better result due to, for example, shadows.
