### ISSUE TITLE
Issue: The device or resource (openscan) is not set up to accept connections on port "The World Wide Web service (HTTP)

### ISSUE THREAD

**Issue by OpenScanFan** [OpenScanEu/OpenScan2#22]
This has been driving up the wall and around the block, I have tried EVERYTHING to get this to work

Cant access the scanner via browser
It worked before, now just doesn't show up anymore...
Any idea what the issue is
![Untitled](https://user-images.githubusercontent.com/101347768/158184515-67836ce3-7cd7-470b-9cc7-9ebf8b832f00.jpg)
?

**Comment by OpenScanFan** [comment]
Been using it for weeks now, it just suddenly stopped being detected from today
Using Ethernet
Using Beta+Arducam
Don't know how to ping
Have no idea how to check address

**Comment by OpenScanFan** [comment]
Hey Sokol, thanks for trying to help, but like I said I have been using it everyday for weeks, no problems at all...just TODAY it went offline.
That documentation is old, the wpa_supplicant.conf file is no longer present in the boot directory

Used the Angry IP Scanner, cant seem to find the PI...hmmm...

![Untitled2](https://user-images.githubusercontent.com/101347768/158199977-a69cda5a-012d-48aa-84a8-f4369a9460fd.jpg)

**Comment by sokol07** [comment]
The wpa_supplicant should be added and edited manually (it should have your WiFi credentials) as described in the docs. The template can be downloaded from the project google drive:
https://drive.google.com/drive/folders/1V_viMNELEG5r0Spcr9WuQKSPY0RPLPbV
Hard to tell why it's not reachable, maybe something caused some kind of a crash - do you have any signs of live from the scanner (lights flashing, etc)?
How are you connecting to it? Scanner to the internet router or directly to your computer?
If the RPi isn't reachable in any way maybe something wrong happened to the uSD card with the OS, you could try flashing the image to another card booting from it and trying to connect the scanner to check this.
Have you updated something befored it stopped working? Windows, Scanner OS or something?

**Comment by sokol07** [comment]
No problem, I'm happy it worked! :)
