### ISSUE TITLE
Issue: Turntable, turning in random directions

### ISSUE THREAD

**Issue by OpenScanFan** [OpenScanEu/OpenScan2#23]
Hey, hope someone can help with this one
When scanning, the turntable does not turn in equal distances, it just jumps all over the show
Any reason for this?

Sample alignment results showing camera positions
![Turntable_Issue](https://user-images.githubusercontent.com/101347768/158398766-7d15c359-43a3-4cd6-a69b-058536c22472.jpg)

**Comment by OpenScanFan** [comment]
Can someone please address this issue? its pretty serious for me @OpenScanEu or Tomasz? Anyone?

**Comment by sokol07** [comment]
I briefly looked through the positions generator in code and I don't see an issue there. Are you sure that the software you're using are drawing this schematic precisely? Maybe it's just a matter of the software ability to detect the position?
Maybe I'll have some more time in the evening, I'll try to investigate the code generator further.

**Comment by OpenScanFan** [comment]
Yes, I am sure the software I am using for reconstruction is calculating camera positions precisely. I can physically see the motor rotating in random positions on the scanner. 

Do you think it could be the voltage setting on the stepper motor driver on the board may be set incorrectly?

Yes please, if you can check it that would be great. thanks

**Comment by sokol07** [comment]
I don't think so - even if the voltage (or rather - current) is set incorrectly a step is a step, I doubt that the stepper is missing steps unless you're scanning extremely heavy and it doesn't have enough power to move.
That's a stupid idea but I made that mistake and realised it after definitely too long time (please, don't laugh at me) - do you have a correct version of the OpenScan set in the setting? OpenScan Classic with Mini in setting is doing really strange things, I guess in the opposite way it is the same.
![image](https://user-images.githubusercontent.com/39523480/159231842-95979e1f-cca5-4d09-ae38-8f76c88999ab.png)

Further thing to check are the stepper parameters - at the default ones my steppers weren't working correctly. Check if the 90 degree rotation (manually by step) is really 90 degree - maybe there is something wrong with the steps/rev settting.

**Comment by yoyo42** [comment]
I had noticed this but I assumed it was an algorithm that covered more angles in fewer images. Seems to work OK anyway.

**Comment by OpenScanEu** [comment]
@OpenScanFan 
![image](https://user-images.githubusercontent.com/57842400/165296150-2886edff-6615-4562-b41d-6fd5714a78ad.png)
Here you can see a comparison of the two approaches (turntable vs optimized).
