### ISSUE TITLE
Auto Preview Update 

### ISSUE THREAD

**Issue by xsiriox** [OpenScanEu/OpenScan2#27]
Hello! I'm using openscan mini with imx230, and I'd like to deactivate auto preview update. I don't want burn the autofocus motor, and the camera is doing a lot of noise because autofocus is working on every preview shot. I'm using the imx519 setup, but with imx230 and autofocus is working fine. Please add the function as in the old version, or tell me what to modify in the code to disable the preview! 

Thank you for the great work!

**Comment by sokol07** [comment]
Are you familiar with the node red?
You should edit the SCAN flow, adding two blocks:
![image](https://user-images.githubusercontent.com/39523480/159875354-2e9e3465-6457-4184-b628-7d6b029cf09a.png)
Code for the added function node:
ON START (this is important!)
```
global.set('enable_preview',true)
```
ON MESSAGE
```
global.set('preview_enable',msg.payload)
```

You should also modify the "enable" function below the marked nodes on the screenshot above:
```
msg.flag = global.get('flag')
if (global.get('flag_pw')== true && global.get('preview_enable')== true){
    return msg
}
```

The "preview enable" switch should be placed in placed in "[Scan] Settings" dashboard:
![image](https://user-images.githubusercontent.com/39523480/159875852-d8929806-58e6-4d56-b4c4-6c175b33a091.png)

And then you should place it wherever you want in the dashboard, for example:
![image](https://user-images.githubusercontent.com/39523480/159876491-30c3aea9-bcc5-4244-b65b-b02c0b6bfed9.png)

**Comment by sokol07** [comment]
I've added this to my fork, included in #20

**Comment by xsiriox** [comment]
Wow! Thankyou!!! 

So fast!!! Il try today!!

**Comment by sokol07** [comment]
No problem, I hope it'll work as expected. :)
I've tested it only with Arducam, if there is any problem - let me know.
