### ISSUE TITLE
Feature Request: Timer

### ISSUE THREAD

**Issue by OpenScanFan** [OpenScanEu/OpenScan2#28]
I recently realized it would be really handy to have a time duration and time remaining for the scan
its because I need to plan my day(s) around scan times, I scan all day everyday

Also maybe a total time duration next to the saved file name?

**Comment by OpenScanFan** [comment]
Thank you for your reply Thomas,
Yes, I use the scanner all day everyday, great scanner

ok, then would it be possible to put a time stamp on the finished file? i.e. the total time it took to do the scan?

**Comment by OpenScanEu** [comment]
@OpenScanFan What do you think about the following:
![image](https://user-images.githubusercontent.com/57842400/164403930-bfe52f11-adad-4481-8b48-9caaea91a280.png)
Where the first number 314 is the remaining time in seconds. And 357s the total estimated time from start to finish. It updates after each photo, but needs roughly 10-20 photos to get a good precision (+- 10% after 10 photos, +- 3% after 20 photos).

would you still want the timestamp on the filename?

**Comment by OpenScanEu** [comment]
I improved the ETA calculation and so it is quite accurate after 5 photos.

**Comment by OpenScanFan** [comment]
Hey Thomas,

Sorry for my late reply,

hmmm....giving the total time in seconds...that may be useful for someone else, but not for me

I need a shorter hand version ie. hours and minutes and then seconds

![Tmer_Request_01](https://user-images.githubusercontent.com/101347768/164913197-89435fb9-bd41-495b-a9f0-d5a6c4ebfe3d.jpg)

**Comment by OpenScanEu** [comment]
@OpenScanFan how about: 
![image](https://user-images.githubusercontent.com/57842400/165082116-d1bd58c8-63ee-4283-b968-acc4dfd9acfc.png)
(But I won't add those numbers to the filename, as it is already long enough ;)

**Comment by OpenScanFan** [comment]
That's good enough for me, thank you so much Thomas, it's a big help
