### ISSUE TITLE
Stop button active when not running the scan

### ISSUE THREAD

**Issue by minimaker-nl** [OpenScanEu/OpenScan2#8]
Minor issue, Normally the stop button is inactive when the scan is not running. But I've had a few times that both the play and stop button on the scan page are clickable. I think it is sometimes when you switch pages (like from settings to scan). But I'm not sure.

This does not have any effect an the functions of the scanner, so this is just a cosmetic issue.

**Comment by OpenScanEu** [comment]
I found the source of this issue: in the code, I used 'enable' instead of 'enableD' ^^ should be fixed with today's beta update
